# Change these first
owner: optbp-monitor # Your GitHub username
repo: optbp-monitor # Your GitHub repository name

# Add your sites here
sites:
  - name: Patient UI
    url: https://pt.optbp.com/
  - name: Clinician UI
    url: https://clin.optbp.com/
  - name: Auth Server
    url: https://auth.optbp.com/Account/LoginWithPasscode
  - name: API Server
    url: https://api.optbp.com/api/practice/additionaldetails/

status-website:
  cname: monitor.optbp.com
  logoUrl: https://www.optbp.com/assets/images/logo.svg
  name: OptBP Monitor
  introTitle: "Welcome to the OptBP Status Page."
  introMessage: This status page uses **real-time** data from our servers. If our servers show no problems, but you are experiencing issues please contact support by visiting optbp.freshdesk.com (https://optbp.freshdesk.com).
  #navbar:
  #  - title: Status
  #    href: /
  #  - title: GitHub
  #    href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
