# Change these first
owner: optbp-monitor # Your GitHub username
repo: optbp-monitor # Your GitHub repository name

# Add your sites here
sites:
  - name: UAT Pt
    url: http://optimise-bp-patient-uat.azurewebsites.net/
  - name: UAT Clin
    url: https://optimise-bp-clinician-uat.azurewebsites.net/
  - name: UAT Auth
    url: https://optimise-bp-auth-uat.azurewebsites.net/Account/LoginWithPasscode

status-website:
  cname: monitor.optbp.com
  logoUrl: https://optimise-bp-auth-uat.azurewebsites.net/images/logo-icon.png
  name: OptBP Monitor
  introTitle: "Welcome to the OptBP Status Page."
  introMessage: This status page uses **real-time** data from our servers. If our servers show no problems, but you are experiencing issues please contact support by visiting optbp.freshdesk.com (https://optbp.freshdesk.com).
  #navbar:
  #  - title: Status
  #    href: /
  #  - title: GitHub
  #    href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
